# Generated by Django 4.0.4 on 2022-05-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomweb', '0002_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
