# Generated by Django 4.0.4 on 2022-05-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomweb', '0004_remove_service_serviceicon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='date',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='purl',
        ),
    ]
