# Generated by Django 4.0.3 on 2022-05-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomweb', '0005_remove_detail_date_remove_detail_purl'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorimage', models.ImageField(upload_to='pics')),
                ('heading', models.CharField(max_length=50)),
                ('subheading', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
